___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
V = np.ones(10)
print(V)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
V = np.arange(0,11)
print(V)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
M = np.zeros((5,5))
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [6]:
# Я обмежила інтервал (від 0 до 5 включно), оскільки при великих значеннях цілих чисел нуль рандомно майже не випадає 
V = np.random.randint(6, size = 20)
print('Вектор з 20 елементів:')
print(V)
e = np.nonzero(V)
print(f'\nІндекси ненульових елементів:\n', e[0])

Вектор з 20 елементів:
[4 5 4 1 0 5 5 1 4 5 3 4 3 5 3 5 1 3 5 1]

Індекси ненульових елементів:
 [ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
s = np.mean(V)
print(f'Середнє значення вектора V -', s)
m = np.median(V)
print(f'\nМедіана вектора V -', m)
std = np.std(V)
print(f'\nСтандартне відхилення вектора V -', std)

Середнє значення вектора V - 3.35

Медіана вектора V - 4.0

Стандартне відхилення вектора V - 1.6515144564913744


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [8]:
M1 = np.random.random((4,2))
print('Матриця 4х2')
print(M1)
M2 = np.random.random((2,2))
print('\nМатриця 2х2')
print(M2)
M_1_2 = np.dot(M1, M2)
print('\nРезультат множення двох матриць')
print(M_1_2)

Матриця 4х2
[[0.46099148 0.2821302 ]
 [0.44996459 0.10465911]
 [0.92393892 0.08417974]
 [0.28629606 0.88900763]]

Матриця 2х2
[[0.49034687 0.39470324]
 [0.34579998 0.70487728]]

Результат множення двох матриць
[[0.32360634 0.380822  ]
 [0.25682984 0.25137431]
 [0.48215991 0.42401807]
 [0.4478032  0.73964326]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [9]:
V = np.reshape(M_1_2, (8))
print('Вектор, отриманий з матриці')
print(V)
V_min = np.min(V)
print(f'\nМінімальне значення вектора - ', V_min)
V_max = np.max(V)
print(f'\nМаксимальне значення вектора- ', V_max)

V[list(V).index(V_max)] = 0
print(f'\nВектор в якому максимальне значення змінено на 0')
print(V)

Вектор, отриманий з матриці
[0.32360634 0.380822   0.25682984 0.25137431 0.48215991 0.42401807
 0.4478032  0.73964326]

Мінімальне значення вектора -  0.2513743068929289

Максимальне значення вектора-  0.7396432604831439

Вектор в якому максимальне значення змінено на 0
[0.32360634 0.380822   0.25682984 0.25137431 0.48215991 0.42401807
 0.4478032  0.        ]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [10]:
K1 = np.correlate(M_1_2[0], M_1_2[1])
print('Кореляція першого рядка матриці до другого рядка -', K1)
K2 = np.correlate(M_1_2[0], M_1_2[2])
print(f'\nКореляція першого рядка матриці до третього рядка -',K2)
K3 = np.correlate(M_1_2[0], M_1_2[3])
print(f'\nКореляція першого рядка матриці до червертого рядка -',K3)

Кореляція першого рядка матриці до другого рядка - [0.17884063]

Кореляція першого рядка матриці до третього рядка - [0.31750542]

Кореляція першого рядка матриці до червертого рядка - [0.14491196]


Дано матрицю. Знайти ранг матриці:

In [11]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матриці - ', r)

Ранг матриці -  3


Знайти визначник матриці:

In [12]:
v = np.linalg.det(a)
print(f'Визначник матриці - ', v)

Визначник матриці -  440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [13]:
z = np.linalg.eig(a)
print(f'Власні значення матриці:')
print(z[0])
print(f'\nВласні вектори матриці:')
print(z[1])

Власні значення матриці:
[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]

Власні вектори матриці:
[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [14]:
a = np.random.randint(0,10,50)
print('Масив a:')
print(a)
print(f'\nВ масиві найчастіше зустрічається число - ', np.bincount(a).argmax())

Масив a:
[3 2 7 1 9 3 0 4 4 7 6 6 1 5 1 2 5 1 4 0 3 8 7 1 8 2 7 8 9 6 6 1 0 1 1 5 5
 1 8 9 3 6 2 3 3 8 6 2 0 3]

В масиві найчастіше зустрічається число -  1


Виведіть лише парні числа, що діляться на 5:

In [15]:
# a = np.random.randint(0,10,50)
# Я збільшила масимальне значення інтервалу з 10 до 100, 
# оскільки в інтервалі рандомних чисел від 0 до 9 немає парних чисел, що діляться на 5 націло 

a = np.random.randint(0,100,50)
print('Масив a:')
print(a)
b = a[a%10==0] 
print('\nПарні числа, які діляться на 5:')
print(b[b!=0])

Масив a:
[26  5 24 74 87 35 48 37  5 58 98 94 41 98 49 82 88 82  0 43 12 41 18 47
 17 52 94 86 63 44 72 50  8 33 99 46 71  7 88 97 24 52 55 90 45 38 52  8
 37 76]

Парні числа, які діляться на 5:
[50 90]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [16]:
#Запишемо систему рівнянь у вигляді двох масивів
A1 = np.array([[2,5], [1,-10]])
A2 = np.array([1,3])
R = np.linalg.solve(A1,A2)
print("Розв'язки системи рівняння:")
print(f'x =', R[0])
print(f'y =', R[1])

Розв'язки системи рівняння:
x = 1.0
y = -0.2
